{% set name = "md-environ" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/md-environ-{{ version }}.tar.gz
  sha256: fe3c2a255af523d6f522831c699336cd71f9d543714067d93206ed35836f1793

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - markdown
    - python >={{ python_min }}

test:
  imports:
    - md_environ
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cmacmackin/md-environ/
  summary: This is an extension to Python-Markdown which allows environment variables to be used in the text.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - awvwgk
